### ISSUE TITLE
Class scrartcl Error: undefined old font command `\it'. \end

### ISSUE THREAD

**Issue by Jowi-Ammerbuch** [Josef-Friedrich/cloze#10]
Example:

```latex
% !TeX program = lualatex
% !TeX encoding = UTF-8 Unicode

\documentclass[11pt,parskip=half]{scrartcl}
\usepackage{cloze}

\begin{document}
	\begin{clozebox}
		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua.
	\end{clozebox}
\end{document}
```

This example produces the following error:  "Class scrartcl Error: undefined old font command `\it'. \end"

My internet research led me to a similar case, see 
https://texwelt.de/fragen/26706/fehlermeldung-undefined-old-font-command-was-tun

With `\documentclass[enabledeprecatedfontcommands]{scrartcl}` I can avoid the error-message, but this only seems to be a makeshift solution. Is there a better solution?

**Comment by Josef-Friedrich** [comment]
can you please try the following command (before the first usage of the environment `clozebox`)

```latex
\def\clozefont{\itshape}
```

**Comment by Jowi-Ammerbuch** [comment]
That works! Thanks a lot for the very fast answer and your great package!

**Comment by Josef-Friedrich** [comment]
Your welcome!
