### ISSUE TITLE
Cloze does not work in math mode

### ISSUE THREAD

**Issue by paternal** [Josef-Friedrich/cloze#3]
Consider the following MWE:

~~~tex
\documentclass{article}

\usepackage{cloze}
\clozeset{hide}
\clozesetfont{}

\begin{document}

One and one is \cloze{two}.
\[1+1=\cloze{2}\]

\end{document}
~~~

The word `two` is hidden and underlined (great).
The letter `2` is neither hidden nor underlined (not great).

Is this an expected behaviour?
Regards,

-- Louis

**Comment by Josef-Friedrich** [comment]
Thank you for your feedback. I must admin that I never tested the package in math mode. This is not the expected behaviour. The letter `2` should be hidden. I think this issue is not easy to fix. That takes time.

**Comment by paternal** [comment]
Thanks !
