### ISSUE TITLE
uline

### ISSUE THREAD

**Issue by atmicmic** [Josef-Friedrich/cloze#6]
Why and where does the cloze Package defines a command "\uline" ?
In the documentation there is nothing about this command...
I have conflicts with other macros

**Comment by atmicmic** [comment]
ok its the dependency ("ulem" package)

**Comment by Josef-Friedrich** [comment]
The plain TeX version of cloze doesn’t load `ulem`.  Maybe you try `\input cloze.tex`. The plain TeX version has only a slightly limited range of functionality.

**Comment by atmicmic** [comment]
ok thank you maybe i will do it that way
This "clozestrike" is such a simple trivial function that is easy to do in
many different ways, but i think you load 3 packages just for that. I dont
like that! Also putting stuff in boxes is easy to do, but ok.

But underlining that way is difficult. I have tried "dashundergaps" (also
loads ulem)
Then i have tried lua-ul together with the censor package, but everywhere
are some problems.
Thank you!


Am Do., 1. Juli 2021 um 22:40 Uhr schrieb Josef Friedrich <
***@***.***>:
