### ISSUE TITLE
color changes to black after cloze command

### ISSUE THREAD

**Issue by wagermn** [Josef-Friedrich/cloze#9]
In the following MWE, "package." should be colored red, but it colored black in the resulting pdf.
```tex
\documentclass{article}
\usepackage{cloze}
\begin{document}
\color{red} The \cloze{cloze} package.
\end{document}
```
![image](https://user-images.githubusercontent.com/2802440/207752803-1e2bb8e1-a993-4d43-8b3b-b814fd2a002d.png)
[The result PDF](https://github.com/Josef-Friedrich/cloze/files/10247680/demo.pdf)

**Comment by Josef-Friedrich** [comment]
Thank you for reporting this bug
